<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Functions (Need)</span></div>

## 1 User defined functions

### 1.1 Named functions that return

In [1]:
def greeting(name):
    if name == 'Batman':
        return 'Hello Batman! So, nice to meet you!'
    else:
        return f'Hello {name}!'

In [2]:
greeting("Super Man")

'Hello Super Man!'

In [3]:
greeting(name="Super Man")

'Hello Super Man!'

In [4]:
greet=greeting(name='Super Man')
print(greet)

Hello Super Man!


In [8]:
def basic_stats(numbers):
    np_numbers=np.array(numbers)
    return np_numbers.min(), np_numbers.max(), np_numbers.mean()

In [6]:
list_min, list_max, list_mean = basic_stats([1, 2, 3, 4, 5])

### 1.2 Named functions that don’t return


A function does not have to return anything. A good example is print()

### 1.3 Anonymous functions

In [9]:
my_short_function = lambda name: f"Hello {name}!"

In [10]:
my_short_function(name="Super Man")

'Hello Super Man!'

In [11]:
numbers=[[9, 0, 10],
         [8, 1, 11],
         [7, 2, 12],
         [6, 3, 13],
         [5, 4, 14],
         [4, 5, 15],
         [3, 6, 16],
         [2, 7, 17],
         [1, 8, 18],
         [0, 9, 19]]

sorted(numbers)                         # Sort by comparing the default key 
                                        # (i.e. the 1st element) 

[[0, 9, 19],
 [1, 8, 18],
 [2, 7, 17],
 [3, 6, 16],
 [4, 5, 15],
 [5, 4, 14],
 [6, 3, 13],
 [7, 2, 12],
 [8, 1, 11],
 [9, 0, 10]]

In [12]:
sorted(numbers, key=lambda x: x[1])     # Sort by comparing a custom key
                                        # that uses the 2nd element

[[9, 0, 10],
 [8, 1, 11],
 [7, 2, 12],
 [6, 3, 13],
 [5, 4, 14],
 [4, 5, 15],
 [3, 6, 16],
 [2, 7, 17],
 [1, 8, 18],
 [0, 9, 19]]

In [13]:
sorted(numbers, key=lambda x: sum(x))   # Sort by comparing a custom key
                                        # that uses the sum of the elements

[[9, 0, 10],
 [8, 1, 11],
 [7, 2, 12],
 [6, 3, 13],
 [5, 4, 14],
 [4, 5, 15],
 [3, 6, 16],
 [2, 7, 17],
 [1, 8, 18],
 [0, 9, 19]]

### 1.4 Optional arguments

In [14]:
def greeting(name='no one'):
    if name == 'Batman':
        return 'Hello Batman! So, nice to meet you!'
    else:
        return f'Hello {name}!'

In [15]:
greeting()

'Hello no one!'

In [16]:
print('I', 'am', 'Batman!')                 # Just for comparison
#> I am Batman!
print('I', 'am', 'Batman!', sep='---')  
#> I---am---Batman!

I am Batman!
I---am---Batman!


## 2 The importance of functions?

### 2.1 An argument for functions


functions are a good idea 

Abstraction of details
- Hiding of 'stuff' = abstraction
Reusability of code--> if encapsulate a chunk of code in a function, it becomes straightforward to reuse rather than re-copying and pasting everytime. this means the code will be shorter and more compact

Maintainability of code = with functions, code is easier to change and maintain 

### 2.2 A word of caution

Having too many functions can make it difficult to read code and also increase computational overheads

## Exercise 1 :  Do you know why?

In [2]:
def greeting(name):
    if name == 'Batman':
        return 'Hello Batman! So, nice to meet you!'
    return f'Hello {name}!'

The code works as expected although it does not have an else statement.


This is beause the return statemetn 'Hello Batman! So, nice to meet you!' will be only be executed when the condition of if mentioned above is true.


Otherwise, when the if condition is not true, it will execute the line of *return f'Hello{name}!*

## Exercise 2 :  Calculator functions

In [87]:
x=np.array([36, 34, 44, 76, 27])
y=np.array([64, 66, 56, 24, 73])

def sum_function(x,y):
    return x+y
print(sum_function(x,y))

[100 100 100 100 100]


In [86]:
def multiply_function(x,y):
    return x*y
print(multiply_function(x,y))

[2304 2244 2464 1824 1971]


In [85]:
def subtract_function(x,y):
    return x-y
print(subtract_function(x,y))

[-28 -32 -12  52 -46]


In [89]:
def division_function(x,y):
    if np.any(y==0):     #syntax should be (y==0).any() or np>any(y==0). SHOULDN"T be y.any()==0 or y.all()!=0
        exit()
    return x/y
print(division_function(x,y))

[0.5625     0.51515152 0.78571429 3.16666667 0.36986301]


## Exercise 3 :  max_info() with NumPy

In [53]:
numberss = [40, 27, 83, 44, 74, 51, 76, 77, 10, 49]

In [52]:
numberss = [40, 27, 83, 44, 74, 51, 76, 77, 10, 49]

def max_info(numberss):
    np_numbers=np.array(numbers)
    return np.argmax(numberss)

print(np.max(numberss), np.argmax(numberss))

# argmax returns indices of the max element of the array in a particular axis.

83 2
