<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Functions (Good)</span></div>

## 1 Check, balances and contingencies

### 1.1 assert

In [4]:
x = 10
assert x >= 0, "x is becoming negative!"

In [5]:
x = -1
assert x >= 0, "x is becoming negative!"

AssertionError: x is becoming negative!

Python has a command called assert that can check a condition and halt the execution if necessary. It also gives the option of printing a message.

The programme will run for as long as the condition is True. If it fails, then an AssertationError is raised, and the programme stops running.



### 1.2 try-except

In [6]:
number=input("Give me a number and I will calculate its square.")
square=int(number)**2              # Convert English to number
print(f'The square of {number} is {square}!')

Give me a number and I will calculate its square.2
The square of 2 is 4!


In [7]:
try:
    number=input("Give me a number and I will calculate its square.")
    square=int(number)**2
    print(f'The square of {number} is {square}!')
except:
    print(f"Oh oh! I cannot square {number}!")

Give me a number and I will calculate its square.3
The square of 3 is 9!


## 2 Some loose ends

### 2.1 Positional, keyword and default arguments

In [9]:
def funny_add(a, b, c=1):
    return a + 10*b + 100*c

#three ‘ways’ to pass a value to an argument. positional, keyword or default. 

In [10]:
funny_add(1, 2)           # Two positional, 1 default
#> 121
funny_add(1, 2, 3)        # Three positional
#> 321
funny_add(a=1, b=2)       # Two keyword, 1 default
#> 121
funny_add(c=3, b=1, a=2)  # Three keyword
#> 312
funny_add(1, c=3, b=2)    # One positional, 2 keyword
#> 321
funny_add(1, b=2)         # One positional, 1 keyword, 1 default
#> 121

121

In [12]:
funny_add(a=2, 1)        

#not work because Python cannot unambiguously figure out what the position of 1 is

SyntaxError: positional argument follows keyword argument (4031747735.py, line 1)

### 2.2 Docstrings

In [13]:
def funny_add(a, b, c=1):
    '''
    A test function to demonstrate how 
    positional, keyword and default arguments 
    work.
    '''
    return a + 10*b + 100*c

In [15]:
help(funny_add)

#Docstrings can be used for writing multiline comments, but the practice is frowned upon by puritans

Help on function funny_add in module __main__:

funny_add(a, b, c=1)
    A test function to demonstrate how 
    positional, keyword and default arguments 
    work.



### 2.3 Function are first class citizens

In [19]:
def my_function(angle, trig_function):
        return trig_function(angle)

my_function(np.pi/2, np.sin)        
#> 1.0
my_function(np.pi/2, np.cos)        
#> 6.123233995736766e-17
my_function(np.pi/2, lambda x: np.cos(2*x))  
#> -1.0

#we can pass a function as an argument to another function

-1.0

### 2.4 More unpacking

In [20]:
x, y, z = [1, 2, 3]
print(x, y, z)

1 2 3


In [21]:
x, y, z = np.array([1, 2, 3])
print(x, y, z)

1 2 3


In [22]:
x, *y, z = np.array([1, 2, 3, 4, 5])
print(x, y, z)

1 [2, 3, 4] 5


In [23]:
x, *_, y = [1, 2, 3, 4, 5]
print(x, y)

1 5


## Exercise 1 :  A better calculator I

In [26]:
x=np.array([36, 34, 44, 76, 27])
y=np.array([64, 66, 56, 24, 73])

In [53]:
def sum_function(x,y):
    if yp.any(y==):
        assert number <101, f"number lesser than 101 expected, got: {number}"
    return x+y
print(sum_function(x,y))

SyntaxError: invalid syntax. Maybe you meant '==' or ':=' instead of '='? (2949972872.py, line 2)

In [39]:
def multiply_function(x,y):
    return x*y
print(multiply_function(x,y))

[2304 2244 2464 1824 1971]


In [50]:
def subtract_function(x,y):
    if y.any()==0:
        assert x >= 0, "x is becoming negative!"
    return x-y
print(subtract_function(x,y))

[-28 -32 -12  52 -46]


In [41]:
def division_function(x,y):
    if y.any==0:
        exit()
    return x/y
print(division_function(x,y))

[0.5625     0.51515152 0.78571429 3.16666667 0.36986301]


## Exercise 2 :  A better calculator II

In [25]:
numberss = [40, 27, 83, 44, 74, 51, 76, 77, 10, 49]
