<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Need)</span></div>

## 1 Lists, Arrays & Dictionaries

### 1.1 Let’s compare

In [2]:
py_super_names = ["Black Widow", "Iron Man", "Doctor Strange"]
py_real_names = ["Natasha Romanoff", "Tony Stark", "Stephen Strange"]

In [9]:
np_super_names = np.array(["Black Widow", "Iron Man", "Doctor Strange"])
np_real_names = np.array(["Natasha Romanoff", "Tony Stark", "Stephen Strange"])

#for list and arrays, orders matter

In [8]:
superhero_info = {"Natasha Romanoff": "Black Widow",
                  "Tony Stark": "Iron Man",
                  "Stephen Strange": "Doctor Strange"
                  }

#Notice how the dictionary very elegantly holds the real and superhero names in one structure while we need two lists (or arrays) for the same data. 

### 1.2 Accessing data from a list (or array)

In [5]:
py_super_names = ["Black Widow", "Iron Man", "Doctor Strange"]
py_real_names = ["Natasha Romanoff", "Tony Stark", "Stephen Strange"]

In [6]:
print(py_real_names[0])

Natasha Romanoff


In [10]:
print(py_super_names[0])

# that data in lists (and arrays) must be accessed using a zero-based index.

Black Widow


In [12]:
print(py_super_names[2])    

# Forward indexing. We need to know the size beforehand for this to work.

Doctor Strange


In [14]:
print(py_super_names[-1])   # Reverse indexing

#Using a negative index allows us to count from the back of the list.

Doctor Strange


### 1.3 Accessing data from a dictionary

In [15]:
superhero_info = {"Natasha Romanoff": "Black Widow",
                  "Tony Stark": "Iron Man",
                  "Stephen Strange": "Doctor Strange"
                  }

In [17]:
print(superhero_info["Natasha Romanoff"])

#Dictionaries hold data (values) paired with a key

Black Widow


In [18]:
superhero_info.values()

dict_values(['Black Widow', 'Iron Man', 'Doctor Strange'])

### 1.4 Higher dimensional lists

In [19]:
py_superhero_info = [['Natasha Romanoff', 'Black Widow'],
                     ['Tony Stark', 'Iron Man'],
                     ['Stephen Strange', 'Doctor Strange']]

## 2 Lists vs. Arrays

### 2.1 Size

In [21]:
py_list_2d = [[1, "A"], [2, "B"], [3, "C"], [4, "D"],
              [5, "E"], [6, "F"], [7, "G"], [8, "H"],
              [9, "I"], [10, "J"]]

np_array_2d = np.array(py_list_2d)      

#We can use the len() function for this.

In [23]:
len(py_list_2d)

#letting know how many list is in the above 

10

In [25]:
len(np_array_2d)

10

In [27]:
np_array_2d.shape

#shape is not a function. IT is rather property or attribute of the NumPy array.

(10, 2)

### 2.2 Arrays are fussy about type

In [29]:
py_list = [1, 1.5, 'A']
np.array(py_list)

#Difference between lists and arrays = arryas like having a single data type while lists are more accommodating.

array(['1', '1.5', 'A'], dtype='<U32')

### 2.3 Adding a number

In [30]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)        

#this setup is reusing the Python List to create a New NumPy array

In [32]:
py_list + 10        # Won't work!

TypeError: can only concatenate list (not "int") to list

In [33]:
np_array + 10

array([11, 12, 13, 14, 15])

### 2.4 Adding another list

In [34]:
py_list_1 = [1, 2, 3, 4, 5]
py_list_2 = [10, 20, 30, 40, 50]

np_array_1 = np.array(py_list_1)
np_array_2 = np.array(py_list_2)

In [35]:
py_list_1 + py_list_2

[1, 2, 3, 4, 5, 10, 20, 30, 40, 50]

In [36]:
np_array_1 + np_array_2

array([11, 22, 33, 44, 55])

### 2.5 Multiplying by a Number

In [37]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)         

In [38]:
py_list*2

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [39]:
np_array*2

array([ 2,  4,  6,  8, 10])

### 2.6 Squaring

In [40]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)

In [41]:
py_list**2                      # Won't work!  

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

In [42]:
np_array**2

array([ 1,  4,  9, 16, 25])

### 2.7 Asking questions

In [43]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)         

In [85]:
py_list == 3 

False

In [46]:
py_list > 3      # Won't work!

TypeError: '>' not supported between instances of 'list' and 'int'

In [47]:
np_array == 3  

array([False, False,  True, False, False])

In [48]:
np_array > 3  

array([False, False, False,  True,  True])

### 2.8 Mathematics

In [49]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)         

In [50]:
sum(py_list)     # sum() is a base Python function

15

In [51]:
max(py_list)     # max() is a base Python function

5

In [52]:
min(py_list)     # min() is a base Python function

1

In [53]:
py_list.sum()   # Won't work!

AttributeError: 'list' object has no attribute 'sum'

In [54]:
np_array.mean()

3.0

In [55]:
np_array.max()

5

In [56]:
np_array.min()

1

## Exercise 1 :  Total recall?

1. Two similarities between lists and arrays.
- order matters for both lists and arrays 
- both are ways of storing data 

2. Two differences between lists and arrays.
- array like having a single data type. *lists are more accommodating.*
- for list, multiplying a number makes a list grow. for array, it multiplies the elements by the number input.

3. What is a dictionary?
- way of storing data. *dictionary is a neat way to store data because you easily access information with a key;*

## Exercise 2 :  Index me

In [65]:
py_list = ["a1", "b2", "c3", "d4", "e5", "f6", "g7", "h8", "i9", "j10"]
                    # Prints 'a1'
                    # Prints 'c3'
                    # Prints 'e5'
                    # Prints 'g7'
print(py_list[8])   # Prints 'i9'
print(py_list[1])
print(py_list[2])
print(py_list[4])
print(py_list[6])

i9
b2
c3
e5
g7


## Exercise 3 :  Capitalise Heros

In [69]:
superhero_info = {"Natasha Romanoff": "Black Widow",
                  "Tony Stark": "Iron Man",
                  "Stephen Strange": "Doctor Strange"
                  }

superhero_info['Tony Stark'] = superhero_info['Tony Stark'].upper()   
superhero_info['Natasha Romanoff'] = superhero_info['Natasha Romanoff'].upper()
superhero_info['Stephen Strange'] = superhero_info['Stephen Strange'].upper()   

In [70]:
print(superhero_info["Natasha Romanoff"])

BLACK WIDOW


In [71]:
print(superhero_info["Tony Stark"])

IRON MAN


In [72]:
print(superhero_info["Stephen Strange"])

DOCTOR STRANGE


## Exercise 4 :  How many ones

In [74]:
numbers=[45, 60, 1, 30, 96, 1, 96, 57, 16, 1,
        99, 62, 86, 43, 42, 60, 59, 1, 1, 35,
        83, 47, 34, 28, 68, 23, 22, 92, 1, 79,
        1, 29, 94, 72, 46, 47, 1, 74, 32, 20,
        8, 37, 35, 1, 89, 29, 86, 19, 43, 61]   

np_array_1 = np.array(numbers) 

In [79]:
numbers == 3 

False

In [83]:
np_array_1 == 1

array([False, False,  True, False, False,  True, False, False, False,
        True, False, False, False, False, False, False, False,  True,
        True, False, False, False, False, False, False, False, False,
       False,  True, False,  True, False, False, False, False, False,
        True, False, False, False, False, False, False,  True, False,
       False, False, False, False, False])

In [92]:
true_array=[False, False,  True, False, False,  True, False, False, False,
        True, False, False, False, False, False, False, False,  True,
        True, False, False, False, False, False, False, False, False,
       False,  True, False,  True, False, False, False, False, False,
        True, False, False, False, False, False, False,  True, False,
       False, False, False, False, False]

np_array_true=np.array(true_array)

In [98]:
sum(np_array_true)

9