<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Good)</span></div>

## 1 Subsetting: Indexing and Slicing

### 1.1 Indexing & Slicing 1D (Lists & Arrays)

In [4]:
#applies to both lists and arrays.

py_list=["a1", "b2", "c3", "d4", "e5",
         "f6", "g7", "h8", "i9", "j10"]
np_array=np.array(py_list)

# Pick one
x = py_list  # OR
x = np_array


#Subsetting means to ‘select’.
#Indexing refers to selecting one element.
#Slicing refers to selecting a range of elements.

### 1.2 Subsetting by masking (Arrays only)

In [9]:
np_array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
my_mask = np_array > 3
print(my_mask)

#One of the most powerful things we can do with NumPy arrays is subsetting by masking.

[False False False  True  True  True  True  True  True  True]


In [10]:
np_array[my_mask]

#The answer to my question is in the form of a ‘Yes’/‘No’ or True/False format. I can use this True/False format to ask NumPy to show me only those that are True by

array([ 4,  5,  6,  7,  8,  9, 10])

In [11]:
np_array[np_array > 3]

#*subsetting by masking only works with NumPy arrays.
#The answer to my question is in the form of a ‘Yes’/‘No’ or True/False format. I can use this True/False format to ask NumPy to show me only those that are True by

array([ 4,  5,  6,  7,  8,  9, 10])

In [12]:
np_array[np_array > 3]

array([ 4,  5,  6,  7,  8,  9, 10])

In [17]:
np_array[(np_array > 3) & (np_array < 8)]         # '&' means 'AND'

#must use the Bitwise NOT(~), Bitwise OR(|) and Bitwise AND(&) when combining masks with NumPy.

array([4, 5, 6, 7])

### 1.3 Indexing & Slicing 2D Lists

In [18]:
py_list_2d = [[1, "A"], [2, "B"], [3, "C"], [4, "D"],
              [5, "E"], [6, "F"], [7, "G"], [8, "H"],
              [9, "I"], [10, "J"]]

In [19]:
py_list_2d[3]        # What is at position 4 (index 3)?

[4, 'D']

In [20]:
py_list_2d[3][0]     # FIRST element at position 4 (index 3)

4

In [22]:
py_list_2d[:3]

[[1, 'A'], [2, 'B'], [3, 'C']]

In [24]:
py_list_2d[:3][0]

#it gives the first of the list you get from py_list_2d[:3].

[1, 'A']

### 1.4 Indexing & Slicing 2D Arrays

In [25]:
np_array_2d = np.array([[1, "A"], [2, "B"], [3, "C"], [4, "D"],
                        [5, "E"], [6, "F"], [7, "G"], [8, "H"],
                        [9, "I"], [10, "J"]])

In [26]:
np_array_2d[3]       # What is at position 4 (index 3)?

array(['4', 'D'], dtype='<U21')

In [27]:
np_array_2d[3, 0]    # FIRST element at position 4 (index 3)

'4'

In [28]:
np_array_2d[:3]

array([['1', 'A'],
       ['2', 'B'],
       ['3', 'C']], dtype='<U21')

In [29]:
np_array_2d[:3, 0]

array(['1', '2', '3'], dtype='<U21')

In [30]:
np_array_2d[:, 0]

array(['1', '2', '3', '4', '5', '6', '7', '8', '9', '10'], dtype='<U21')

### 1.5 Growing lists

In [33]:
x=[1]*10
x              

[1, 1, 1, 1, 1, 1, 1, 1, 1, 1]

In [32]:
x=[1]
x= x + [2]
x= x + [3]
x= x + [4]
x

[1, 2, 3, 4]

In [34]:
x=[1]
x+= [2]
x+= [3]
x+= [4]
x

[1, 2, 3, 4]

In [35]:
x=[1]
x+= [2, 3, 4]
x

[1, 2, 3, 4]

In [36]:
x=[1]
x= [2, 3, 4] + x
x

[2, 3, 4, 1]

In [37]:
x=[1]
x.append(2)
x.append(3)
x.append(4)
x

[1, 2, 3, 4]

## 2 Some loose ends

### 2.1 Tuples

In [41]:
a=(1, 2, 3)     # Define tuple

#tuple. Tuples are similar to lists, except they use ( ) and cannot be changed after creation.

## The following will NOT work BC WE CANNOT CHANGE DATA
#a[0]=-1
#a[0] += [10]

In [39]:
print(a[0])    # Access data

1


### 2.2 Be VERY careful when copying

In [42]:
x=[1, 2, 3]
y=x           # DON'T do this!
z=x           # DON'T do this!

#shoudl rather do something like below

In [43]:
x=[1, 2, 3]
y=x.copy()
z=x.copy()

## Exercise 1 :  Total recall?

|Term|Brief Description|
|----|---------|
|Subsetting|it's like "select." we can select a subset from the list of the data|
|Indexing|way of selecting. can select just single element|
|Slicing|select a range of elements|
|Masking|*replaces the values of the rows where the condition evaluates to True*|

## Exercise 2 :  Show me the ‘odd’ letters

In [44]:
np_array_2d = np.array([[1, "A"], [3, "C"], [2, "B"], [4, "D"],
                        [5, "E"], [7, "G"], [6, "F"], [8, "H"],
                        [10, "J"], [9, "I"]])

In [57]:
#NOT DONE YET